### PR TITLE
carousel obj load

### PR DESCRIPTION
**Pull request by PratikTalkingLands**

### CODE REVIEW

**Comment by PratikTalkingLands** [comment]
Merge these two pull request into your repository, in a separate branch

**Comment by Chandru-TalkingLands** [comment]
ygghighi

**Comment by Chandru-TalkingLands** [comment]
kkbk

**Comment by Chandru-TalkingLands** [comment]
kljkljkl

**Comment by Chandru-TalkingLands** [comment]
kbjhg

**Pull request closed without merging**
